export const TENANT_OPTIONS = [
  { label: 'Main (www)', value: 'www' },
  { label: 'London (london)', value: 'london' },
  { label: 'United Kingdom (uk)', value: 'uk' },
  { label: 'Los Angeles (la)', value: 'la' },
  { label: 'New York (ny)', value: 'ny' },
  { label: 'Berlin (ber)', value: 'ber' },
  { label: 'Nashville (nsh)', value: 'nsh' },
  { label: 'Tokyo (tyo)', value: 'tyo' },
  { label: 'Barcelona (bcn)', value: 'bcn' },
  { label: 'Seattle (sea)', value: 'sea' },
  { label: 'Miami (mia)', value: 'mia' },
  { label: 'Houston (hou)', value: 'hou' },
  { label: 'Sydney (syd)', value: 'syd' },
  { label: 'Lisbon (lis)', value: 'lis' },
  { label: 'San Francisco (sf)', value: 'sf' },
  { label: 'Singapore (sg)', value: 'sg' },
  { label: 'Portland (pdx)', value: 'pdx' },
  { label: 'Global Hub (edu)', value: 'edu' },
];
