import sqlite3 from 'sqlite3';
import { Client } from 'pg';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env.local') });

const DB_PATH = path.resolve(process.cwd(), 'garnish-local.db');
const PG_URL: string = process.env.DATABASE_URL || process.env.DATABASE_URI || '';

if (!PG_URL) {
  console.error('ERROR: DATABASE_URL not found in .env.local');
  process.exit(1);
}

async function runMigration() {
  console.log('=== Starting Fast Batched SQLite -> Neon Postgres Migration ===');
  console.log(`SQLite Database: ${DB_PATH}`);
  console.log(`Neon URL: ${PG_URL.split('@')[1]}`);

  // Connect to SQLite
  const sqliteDb = new sqlite3.Database(DB_PATH);
  const getSqliteRows = (query: string, params: any[] = []): Promise<any[]> => {
    return new Promise((resolve, reject) => {
      sqliteDb.all(query, params, (err, rows) => {
        if (err) reject(err);
        else resolve(rows);
      });
    });
  };

  // Connect to Neon Postgres
  const pgClient = new Client({
    connectionString: PG_URL,
  });
  await pgClient.connect();
  console.log('Connected to Neon PostgreSQL.');

  try {
    const sqliteTables = await getSqliteRows(
      `SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'`
    );

    const orderedTables = [
      'users',
      'media',
      'pages',
      'courses',
      'posts',
      'users_allowed_tenants',
      'users_sessions',
      'pages_blocks_course_grid',
      'pages_blocks_rich_text',
      'pages_blocks_hero',
      'pages_blocks_hero_buttons',
      'pages_blocks_feature_grid',
      'pages_blocks_feature_grid_features',
      'pages_blocks_cta',
      'pages_rels',
      'payload_preferences',
      'payload_preferences_rels',
      'payload_migrations',
      'payload_kv',
      'payload_locked_documents',
      'payload_locked_documents_rels'
    ];

    for (const t of sqliteTables) {
      if (!orderedTables.includes(t.name)) {
        orderedTables.push(t.name);
      }
    }

    let totalRowsMigrated = 0;

    for (const tableName of orderedTables) {
      const checkExists = sqliteTables.find((t) => t.name === tableName);
      if (!checkExists) continue;

      const tableInfo = await getSqliteRows(`PRAGMA table_info("${tableName}")`);
      if (!tableInfo || tableInfo.length === 0) continue;

      const colDefs = tableInfo.map((col: any) => {
        const name = col.name;
        const type = col.type.toUpperCase();

        if (name === 'id') {
          if (type.includes('INT')) {
            return `"id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY`;
          } else {
            return `"id" VARCHAR PRIMARY KEY`;
          }
        }

        let pgType = 'TEXT';
        if (type.includes('INT')) {
          pgType = 'INTEGER';
        } else if (type.includes('NUMERIC') || type.includes('REAL') || type.includes('DOUBLE') || type.includes('FLOAT')) {
          pgType = 'DOUBLE PRECISION';
        } else if (type.includes('BOOL')) {
          pgType = 'BOOLEAN';
        } else if (type.includes('DATE') || type.includes('TIME')) {
          pgType = 'TIMESTAMP WITH TIME ZONE';
        }

        return `"${name}" ${pgType}`;
      });

      const createTableSql = `CREATE TABLE IF NOT EXISTS "${tableName}" (\n  ${colDefs.join(',\n  ')}\n);`;
      await pgClient.query(createTableSql);

      const rows = await getSqliteRows(`SELECT * FROM "${tableName}"`);
      if (rows.length === 0) {
        console.log(`Table [${tableName}]: Ready (0 rows to migrate).`);
        continue;
      }

      const validCols = tableInfo.map((col: any) => col.name);
      const colListSql = validCols.map((c) => `"${c}"`).join(', ');

      // Insert in chunks of 50 rows per query for extreme speed
      const CHUNK_SIZE = 50;
      let insertedForTable = 0;

      for (let i = 0; i < rows.length; i += CHUNK_SIZE) {
        const chunk = rows.slice(i, i + CHUNK_SIZE);
        const valuePlaceholders: string[] = [];
        const flatValues: any[] = [];

        chunk.forEach((row, rowIdx) => {
          const rowPlaceholders: string[] = [];
          validCols.forEach((col, colIdx) => {
            const paramIdx = rowIdx * validCols.length + colIdx + 1;
            rowPlaceholders.push(`$${paramIdx}`);
            let val = row[col];
            if (val === '' && (col.endsWith('_id') || col === 'id' || col.includes('order'))) {
              val = null;
            }
            flatValues.push(val);
          });
          valuePlaceholders.push(`(${rowPlaceholders.join(', ')})`);
        });

        const batchInsertQuery = `INSERT INTO "${tableName}" (${colListSql}) VALUES ${valuePlaceholders.join(', ')} ON CONFLICT DO NOTHING`;
        try {
          const res = await pgClient.query(batchInsertQuery, flatValues);
          insertedForTable += res.rowCount || chunk.length;
          totalRowsMigrated += res.rowCount || chunk.length;
        } catch (err: any) {
          // Fallback to row-by-row insert for this chunk if batch insert fails on type issues
          for (const row of chunk) {
            const singlePlaceholders = validCols.map((_, idx) => `$${idx + 1}`).join(', ');
            const singleQuery = `INSERT INTO "${tableName}" (${colListSql}) VALUES (${singlePlaceholders}) ON CONFLICT DO NOTHING`;
            const singleVals = validCols.map((col) => {
              let val = row[col];
              if (val === '' && (col.endsWith('_id') || col === 'id' || col.includes('order'))) {
                return null;
              }
              return val;
            });
            try {
              await pgClient.query(singleQuery, singleVals);
              insertedForTable++;
              totalRowsMigrated++;
            } catch (singleErr: any) {
              // Ignore duplicate or constraint check
            }
          }
        }
      }

      console.log(`Table [${tableName}]: Migrated ${insertedForTable} / ${rows.length} rows.`);

      // Update sequence for ID
      const idCol = tableInfo.find((col: any) => col.name === 'id');
      if (idCol && idCol.type.toUpperCase().includes('INT')) {
        try {
          await pgClient.query(`
            DO $$
            DECLARE
              max_id INTEGER;
            BEGIN
              SELECT coalesce(max(id), 0) + 1 INTO max_id FROM "${tableName}";
              EXECUTE 'ALTER TABLE "${tableName}" ALTER COLUMN id RESTART WITH ' || max_id;
            EXCEPTION WHEN OTHERS THEN
            END $$;
          `);
        } catch (e) {}
      }
    }

    console.log('\n=== Fast SQLite -> Neon PostgreSQL Migration Complete ===');
    console.log(`Total rows successfully migrated: ${totalRowsMigrated}`);
  } finally {
    sqliteDb.close();
    await pgClient.end();
  }
}

runMigration().catch((err) => {
  console.error('Fatal error during migration:', err);
  process.exit(1);
});
